#
# Copyright 2021 JSquad AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

dist: focal

services:
  - docker

cache:
  directories:
    - .autoconf
    - $HOME/.m2

before_install:
  - echo $JAVA_HOME
  - which java
  - sudo rm -rf /usr/local/lib/jvm/
  - sudo apt-get install -y openjdk-11-jdk-headless
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
  - which java
  - java -version
  - $JAVA_HOME/bin/java -version
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - sudo curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.zip
  - unzip -qq apache-maven-3.6.1-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.6.1
  - export PATH=$M2_HOME/bin:$PATH
  - source setup_environment_variables.sh
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"
  - sudo apt-get update
  - sudo apt-get install kubectl=1.20.1-00 -y
  - curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https --yes
  - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
  - sudo apt-get update
  - sudo apt-get install helm -y
  - sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common wget -y
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get install docker-ce docker-ce-cli containerd.io -y
  - docker --version
  - docker run hello-world

jobs:
  include:
    - stage: build and run unit/system tests
      script:
        - travis_wait 60 mvn clean install
    - stage: run integration tests in Docker
      script:
        - mvn clean install -DskipTests
        - source setup_docker_integration_environment.sh
        - docker-compose -f service/src/test/resources/docker-compose-int.yaml build --force
        - travis_wait 60 mvn verify -Pintegrationtests
    - stage: run integration tests in Kubernetes
      script:
        - source setup_kubernetes_integration_environment.sh
        - docker-compose -f service/src/test/resources/docker-compose-k8-integration.yaml build --force
        - travis_wait 60 mvn verify -Pintegrationtests
    - stage: push OpenBank to dockerhub on master branch after an merge
      if: branch = master
      script:
        - mvn clean install -DskipTests
        - cd service && docker build -f Dockerfile --no-cache -t openbank-spring .
        - docker tag openbank-spring:latest jsquadab/openbank-spring:latest
        - docker push jsquadab/openbank-spring:latest
env:
  global:
    - SH=bash
    - secure: kT+kPtRx05Epih2BDyUPdb190gJYhABBa0gOAvnn1nvpBCgCm3Uq2PM1aTMNOpyPtVBPh5r9amJOo99Cm8vUC3/12UiUHstACfCNoWTBUhu/rNOYx6w8oPzEmo5lGwXS3/8s1GnTDlwbzmYvOHV2vflyxx3UTlrdH79gsCKIUME3vMaoJ6DnMFeLrBuyzWqwHvXtS8xCxOGHxS3WmTMtxnIqRJ7iNhmvphVbB+ocXvihxoYiDKw5Feo+Fda51UFNyvByHAsdaoJCgGTEA6n+sY6Kfmeohet3qYs/1samQqPj4sutGtiYHSRkp6SpcdM4oTHCuLZQ37ixmdRZdziHcPPWngXRXG/m3gQib6StvJ/fno63I5jzuq//Hk9noal/g7gNcoAYuNAxhmwczyEgrdbUpvt1E21t++1V8KJASuriyfEnr/UKnyfQTxodP1AZbVut7IwUPR14KR1y8VFd8BuAM+mJfux3N04HUc/MkwinaunjthvdVffCcV8KCVMbK5MR/RL/Zg1i7e1xhTckpJIoYEZBgQf7fXUKwdKX+jKAFBXGEgegm3DqzqIEGLMp3zpt6VNNt+SUUfOo89jljxc2vSoTvOx06RtLRrD+iHT74uBslnf9BEBWlHL4Ms8wOKoPrQCsbPJuotGX2zw8L3ONEwetwWuX64aH5MBN1nM=
