openapi: 3.0.1
info:
  title: OpenBank API
  description: "This is an local HTTPS OpenBank server. You can find out more about\
    \ OpenBank at [http://jsquad.se](http://jsquad.se)."
  termsOfService: http://jsquad.se/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: "1"
servers:
- url: https://localhost:8443
  description: Local OpenBank API server.
paths:
  /api/update/client/information:
    put:
      summary: "Update client information, mock implementation"
      description: Update the client information based with common constraint vaidation
        for ClientApi xsd model.
      operationId: updateClientInformation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientInformationRequest'
      responses:
        "200":
          description: Get ClientApi model as base response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientInformationResponse'
        "400":
          description: Bad content
          content:
            text/plain:
              schema:
                type: string
                example: ClientApi payload contains bad content.
        "500":
          description: Severe system failure has occured!
          content:
            text/plain:
              schema:
                type: string
                example: Severe system failure has occured!
  /api/get/client/info/:
    get:
      summary: Get client by client request body
      description: Get the ClientAPI response object with uniqueue personal identification
        number as part of the request body.
      operationId: getClientInformationByRequestBody
      requestBody:
        description: ClientRequest body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientRequest'
        required: true
      responses:
        "200":
          description: The client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientApi'
        "400":
          description: Invalid personal identification number
          content:
            text/plain:
              schema:
                type: string
                example: Invalid personal identification number.
        "404":
          description: Client not found.
          content:
            text/plain:
              schema:
                type: string
                example: Client not found.
        "500":
          description: Severe system failure has occured!
          content:
            text/plain:
              schema:
                type: string
                example: Severe system failure has occured!
  /api/date/time/{dateTime}:
    get:
      summary: Get date time
      description: Get the date time RFC3339 string
      operationId: getDateTime
      parameters:
      - name: dateTime
        in: path
        description: The get date time.
        required: true
        schema:
          type: string
        example: 2019-11-01T00:00:00ZZ
      responses:
        "200":
          description: The date time
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DateTime'
        "400":
          description: Date time
          content:
            text/plain:
              schema:
                type: string
                example: Invalid date time format.
        "500":
          description: Severe system failure has occured!
          content:
            text/plain:
              schema:
                type: string
                example: Severe system failure has occured!
  /api/client/info/{personIdentification}:
    get:
      summary: Get client by person identification number
      description: Get the ClientAPI response object with uniqueue personal identification
        number as parameter argument.
      operationId: getClientInformation
      parameters:
      - name: personIdentification
        in: path
        description: The person identification number
        required: true
        schema:
          type: string
        example: 191212121212
      responses:
        "200":
          description: The client
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientApi'
        "400":
          description: Invalid personal identification number
          content:
            text/plain:
              schema:
                type: string
                example: Invalid personal identification number.
        "404":
          description: Client not found.
          content:
            text/plain:
              schema:
                type: string
                example: Client not found.
        "500":
          description: Severe system failure has occured!
          content:
            text/plain:
              schema:
                type: string
                example: Severe system failure has occured!
  /api/get/hello/world:
    get:
      summary: Get hello world by the remote http server
      description: Get The hello world by the remote HTTP REST server
      operationId: getHelloWorld
      responses:
        "200":
          description: Hello world
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorldApiResponse'
        "500":
          description: Severe system failure has occured!
          content:
            text/plain:
              schema:
                type: string
                example: Severe system failure has occured!
  /api/openbank/start/slow/batch/mock:
    get:
      operationId: getOpenBankBatchStatus
      responses:
        "200":
          description: default response
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    AccountApi:
      type: object
      properties:
        balance:
          type: integer
          format: int64
        accountTransactionList:
          type: array
          items:
            $ref: '#/components/schemas/AccountTransactionApi'
    AccountTransactionApi:
      required:
      - message
      - transactionType
      type: object
      properties:
        transactionType:
          type: string
          enum:
          - DEPOSIT
          - WITHDRAWAL
        message:
          type: string
    ClientInformationResponse:
      required:
      - clientType
      - person
      type: object
      properties:
        person:
          $ref: '#/components/schemas/PersonApi'
        accountList:
          type: array
          items:
            $ref: '#/components/schemas/AccountApi'
        clientType:
          $ref: '#/components/schemas/ClientTypeApi'
    ClientTypeApi:
      required:
      - country
      - specialOffers
      - type
      type: object
      properties:
        type:
          type: string
          enum:
          - REGULAR
          - PREMIUM
          - FOREIGN
        specialOffers:
          type: string
        rating:
          type: integer
          format: int64
        premiumRating:
          type: integer
          format: int64
        country:
          type: string
    PersonApi:
      required:
      - firstName
      - lastName
      - mail
      - personIdentification
      type: object
      properties:
        personIdentification:
          type: string
          description: Person identification number
          example: "191212121212"
        firstName:
          type: string
          description: Firstname
          example: John
        lastName:
          type: string
          description: Lastname
          example: Doe
        mail:
          type: string
          description: Email address
          example: john.doe@mail.com
      description: "PersonAPI contains person's firstname, lastname and email address\
        \ information."
    ClientInformationRequest:
      type: object
      properties:
        person:
          $ref: '#/components/schemas/PersonApi'
        accountList:
          type: array
          items:
            $ref: '#/components/schemas/AccountApi'
        clientType:
          $ref: '#/components/schemas/ClientTypeApi'
    ClientData:
      required:
      - personIdentificationNumber
      type: object
      properties:
        personIdentificationNumber:
          type: string
          description: The client person identification number.
          example: "191212121212"
    ClientRequest:
      required:
      - clientData
      type: object
      properties:
        clientData:
          $ref: '#/components/schemas/ClientData'
      description: The client request body.
    ClientApi:
      required:
      - clientType
      - person
      type: object
      properties:
        person:
          $ref: '#/components/schemas/PersonApi'
        accountList:
          type: array
          items:
            $ref: '#/components/schemas/AccountApi'
        clientType:
          $ref: '#/components/schemas/ClientTypeApi'
    DateTime:
      required:
      - dateTime
      type: object
      properties:
        dateTime:
          type: string
          description: Date time
          example: 2019-11-05T11:33:11ZZ
    WorldApiResponse:
      required:
      - message
      type: object
      properties:
        message:
          type: string
  securitySchemes:
    basicScheme:
      type: http
      scheme: basic
